# Generated by Django 6.0.3 on 2026-04-07 05:16

from django.db import migrations


def create_user_profiles(apps, schema_editor):
    """Create UserProfile for all existing users"""
    UserProfile = apps.get_model('store', 'UserProfile')
    User = apps.get_model('auth', 'User')
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles),
    ]
